### ISSUE TITLE
Using input instead

### ISSUE THREAD

**Issue by Saimokore** [JDawgtor/WASD-Detection#1]
First, i liked this datapack a lot, but I have noticed that one problem with your WASD detection is that it doesn't detect player inputs when hes is agaisn't a wall, or when he doesnt actually move.

So i used this predicate to fix this issue:

`{
  "condition": "minecraft:entity_properties",
  "entity": "this",
  "predicate": {
    "type_specific": {
      "type": "minecraft:player",
      "stats": [],
      "input": {
        "forward": true
      }
    }
  }
}`

This way it detects directly from the input and it seems to work fine, so i ask, did you chose to not use this method? If so, does it have any downsides?

**Comment by JDoinkus** [comment]
The reason I didn't use this is only because it hasn't existed till the most recent Minecraft update. So this method was the best I could do before input detection was implemented. So I may close this repository and make a new better one using the new predicates :)

**Comment by Saimokore** [comment]
Yeah i realized just after sending, as ive tested just changing the predicates works pretty well
